{"Type":2,"Message":"System.Exception: this is test exception\r\n   at MyRecipes.Controllers.RecipesController.Overview(String title) in C:\\Sources\\NetGroup2\\MyRecipes\\MyRecipes\\Controllers\\RecipesController.cs:line 29\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at MyRecipes.Custom.RequestResponseLogMiddleware.Invoke(HttpContext httpContext) in C:\\Sources\\NetGroup2\\MyRecipes\\MyRecipes\\Custom\\RequestResponseLogMiddleware.cs:line 22\r\n   at MyRecipes.Custom.ExceptionLoggingMiddleware.Invoke(HttpContext httpContext, ILogService logService) in C:\\Sources\\NetGroup2\\MyRecipes\\MyRecipes\\Custom\\ExceptionLoggingMiddleware.cs:line 22","DateCreated":"2021-04-12T18:49:47.0395596+02:00"}
{"Type":2,"Message":"System.Exception: this is test exception\r\n   at MyRecipes.Controllers.RecipesController.Overview(String title) in C:\\Sources\\NetGroup2\\MyRecipes\\MyRecipes\\Controllers\\RecipesController.cs:line 29\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at MyRecipes.Custom.RequestResponseLogMiddleware.Invoke(HttpContext httpContext) in C:\\Sources\\NetGroup2\\MyRecipes\\MyRecipes\\Custom\\RequestResponseLogMiddleware.cs:line 22\r\n   at MyRecipes.Custom.ExceptionLoggingMiddleware.Invoke(HttpContext httpContext, ILogService logService) in C:\\Sources\\NetGroup2\\MyRecipes\\MyRecipes\\Custom\\ExceptionLoggingMiddleware.cs:line 22","DateCreated":"2021-04-12T18:52:30.7626097+02:00"}
{"Type":2,"Message":"System.Exception: this is test exception\r\n   at MyRecipes.Controllers.RecipesController.Overview(String title) in C:\\Sources\\NetGroup2\\MyRecipes\\MyRecipes\\Controllers\\RecipesController.cs:line 29\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at MyRecipes.Custom.RequestResponseLogMiddleware.Invoke(HttpContext httpContext) in C:\\Sources\\NetGroup2\\MyRecipes\\MyRecipes\\Custom\\RequestResponseLogMiddleware.cs:line 22\r\n   at MyRecipes.Custom.ExceptionLoggingMiddleware.Invoke(HttpContext httpContext, ILogService logService) in C:\\Sources\\NetGroup2\\MyRecipes\\MyRecipes\\Custom\\ExceptionLoggingMiddleware.cs:line 22","DateCreated":"2021-04-12T18:55:09.8004697+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/\"}","DateCreated":"2021-04-12T19:10:49.2395489+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:12:36.2491476+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Recipes/Details/19\"}","DateCreated":"2021-04-12T19:13:22.0456029+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:14:10.1792097+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Auth/SignIn\"}","DateCreated":"2021-04-12T19:14:39.6237035+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:14:45.0043102+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Auth/SignIn\"}","DateCreated":"2021-04-12T19:15:04.6885969+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:15:49.6844209+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Auth/SignIn\"}","DateCreated":"2021-04-12T19:16:04.2015726+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"302\"}","DateCreated":"2021-04-12T19:16:13.8474531+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/\"}","DateCreated":"2021-04-12T19:16:15.9277623+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:16:17.5583516+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/\"}","DateCreated":"2021-04-12T19:40:24.2757959+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:40:31.9918863+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Recipes/ManageOverview\"}","DateCreated":"2021-04-12T19:40:36.2114759+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:40:36.4256892+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Recipes/Create\"}","DateCreated":"2021-04-12T19:40:38.0788576+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:40:38.2703736+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Recipes/Create\"}","DateCreated":"2021-04-12T19:40:49.7219467+02:00"}
{"Type":0,"Message":"User with id Id: 4 created recipe Test recipe","DateCreated":"2021-04-12T19:40:50.2117177+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"302\"}","DateCreated":"2021-04-12T19:40:50.2330558+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Recipes/ManageOverview\"}","DateCreated":"2021-04-12T19:40:50.2490841+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:40:50.2889082+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Recipes/ManageOverview\"}","DateCreated":"2021-04-12T19:42:57.4638599+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:42:57.5875246+02:00"}
{"Type":0,"Message":"{\"RequestPath\":\"/Recipes/Create\"}","DateCreated":"2021-04-12T19:43:03.444836+02:00"}
{"Type":0,"Message":"{\"ResponseStatusCode\":\"200\"}","DateCreated":"2021-04-12T19:43:03.51041+02:00"}
